name: Milvasoft.Components.OpenApi Nuget Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Components/Milvasoft.Components.OpenApi/**'
      - '**/Directory.Build.props'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/Components/Milvasoft.Components.OpenApi/**'
      - '**/Directory.Build.props'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}
      - name: Restore Milvasoft.Components.OpenApi project dependencies
        run: dotnet restore src/Components/Milvasoft.Components.OpenApi/Milvasoft.Components.OpenApi.csproj
      - name: Build Milvasoft.Components.OpenApi project
        run: dotnet build src/Components/Milvasoft.Components.OpenApi/Milvasoft.Components.OpenApi.csproj --no-restore --configuration Release
      - name: Pack Milvasoft.Components.OpenApi project
        run: dotnet pack src/Components/Milvasoft.Components.OpenApi/Milvasoft.Components.OpenApi.csproj --no-build --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -o .
      - name: Publish package to NuGet
        run: dotnet nuget push *.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
